# Use the official Python image as a base
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Python script to the container
COPY high_cpu.py .

# Run the Python script
CMD ["python", "high_cpu.py"]
